### ISSUE TITLE
【求助】Docker Compose 想用另外部署的 MySQL ，而不是内置的，请问该如何配置？

### ISSUE THREAD

**Issue by xkloveme** [blossom-editor/blossom#55]

**Comment by xkloveme** [comment]
解决了

```
version: "3"

networks:
    1panel-network:
        external: true

services:
    blossom:
        container_name: blossom-backend
        image: jasminexzzz/blossom:latest
        volumes:
            - /opt/1panel/apps/mkdocs-material/mkdocs-material/data/:/home/bl/
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/blossom?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8  # 转义连字符
            SPRING_DATASOURCE_USERNAME: blossom
            SPRING_DATASOURCE_PASSWORD: xxxxxx
            PROJECT_IAAS_BLOS_DEFAULT_PATH: /home/bl/img/  # 修正连接角括号问题
        labels:
            createdBy: xkloveme
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9999/sys/alive"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 5s
        ports:
            - 9999:9999
        networks:
            - 1panel-network
        restart: always
```
