### ISSUE TITLE
图片资源配置

### ISSUE THREAD

**Issue by q2316367743** [blossom-editor/blossom#8]
我的图片配置

```yaml
  iaas:
    os-type: blossom
    blos:
      # 请以 /pic 结尾, 如果你在 nginx 中配置有代理, 注意别忘了添加你的代理路径
      domain: "https://blossom-esion.tocmcc.cn/bl/pic/"
      # 请以 / 开头, / 结尾, 简短的路径在文章中有更好的显示效果, 过长一定程度会使文章内容混乱
      default-path: "/home/esion/Appliaction/blossom/bl/img/"
```

之后上传完图片路径是

```
https://blossom-esion.tocmcc.cn/bl/pic/home/esion/Appliaction/blossom/bl/img/U1/avatar.png
```

是不是图片需要自己配置反向代理，代理这个目录啊
