### ISSUE TITLE
七牛云无法使用

### ISSUE THREAD

**Issue by q2316367743** [blossom-editor/blossom#9]
配置
```yml
  iaas:
    os-type: qiniu
    kodo:
      access-key: *****************************************************
      secret-key: *****************************************************
      bucket-name: static-***-***
      domain: https://static.***.***
      default-path: /blog
```
得到了链接

```
https://static.***.***/blog/U1/Snipaste_2022-12-09_11-07-18.png
```
但是并未上传

上传时也报错了：

```plaintext
POST https://upload.qiniup.com/mk
blk/285575 {ResponseInfo:com.qini
u.http.Response@1a9e617a,status:4
00,reqId:Z9IAAABc3te98YgX,xlog:
X-Log,xvia:,adress:upload.qiniu
p.c0m/157.0.149.246:443,
duratio
n:0.229000 s,error:incorrect reg
ion,please use up-z2.qiniup.com,
bucket is:static-***-*** err
or:incorrect region,please use u
p-z2.qiniup.com,bucket is:stati
c-esion-xyz}
```
